favicon: null
name: systematic approach
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.7627022
  brandStrength: 0.4028822
  lightness: 0.6998747
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  rhythmicContrast: 0.75
typography_spectrum: 0.6299369134940207
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3571429
analytics:
  twitter: null
  google: null
  facebook: null
